import React from 'react';
import Head from 'next/head';
import Layout from '@/components/templates/bodyLayout/layout';
import AboutTemplate from '@/components/templates/about/aboutTemplate';

export default function About() {
  const [hydrated, setHydrated] = React.useState<boolean>(false);

  React.useEffect(() => {
    setHydrated(true);
  }, []);

  if (!hydrated) return null;

  return (
    <Layout activeTab={'about'}>
      <>
        <Head>
          <title>NEXXOS | El lado correcto de la educación</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AboutTemplate />
      </>
    </Layout>
  );
}
