import React from 'react';
import Head from 'next/head';
import ContactTemplate from '@/components/templates/contact/contactTemplate';
import Layout from '@/components/templates/bodyLayout/layout';

export default function Contact() {
  const [hydrated, setHydrated] = React.useState<boolean>(false);

  React.useEffect(() => {
    setHydrated(true);
  }, []);

  if (!hydrated) return null;

  return (
    <Layout activeTab={'contact'}>
      <>
        <Head>
          <title>Nexxos | El lado correcto de la educación</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ContactTemplate />
      </>
    </Layout>
  );
}
