import React from 'react';
import Head from 'next/head';
import FourOFourLayout from '@/components/templates/fourOFour/fourOFourLayout';

export default function FourOFour() {
  return (
    <>
      <Head>
        <title>404 - Nexxos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FourOFourLayout />
    </>
  );
}
