import React from "react";
import Head from "next/head";
import Layout from "@/components/templates/bodyLayout/layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>NEXXOS | Mas educacion, mas futuro.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  );
}
